/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:3fc8996a-e357-442e-9a1a-1157689d2508",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_AzHLezPqk",
    "aws_user_pools_web_client_id": "67ukid5ufkjb8u8nloke4vpa0u",
    "oauth": {}
};


export default awsmobile;
